Correction finale de main.dart et liaison avec login et chef_ia

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -3,6 +3,9 @@ workflows:
     name: shinra_ia Android Build
     max_build_duration: 60
 
+    environment:
+      flutter: 3.44.2
+
     triggering:
       events:
         - push
@@ -19,6 +22,19 @@ workflows:
       - name: Get packages
         script: |
           flutter pub get
+
+      - name: Check Gemini API key
+        script: |
+          if [ -z "$GEMINI_API_KEY" ]; then
+            echo "ERROR: GEMINI_API_KEY missing"
+            exit 1
+          fi
+
+      - name: Build APK Release
+        script: |
+          flutter build apk --release \
+          --dart-define=GEMINI_API_KEY=$GEMINI_API_KEY \
+          --dart-define=GEMINI_MODEL=$GEMINI_MODEL
 
     artifacts:
       - build/app/outputs/flutter-apk/app-release.apk
